create table produto (
	idProduto INT,
	nome VARCHAR(14),
	marca VARCHAR(10),
	valor DECIMAL(7,2)
);
insert into produto (idProduto, nome, marca, valor) values (1, 'Pasta Térmica', 'Evga', 2266.76);
insert into produto (idProduto, nome, marca, valor) values (2, 'Gabinete', 'G.Skill', 3744.07);
insert into produto (idProduto, nome, marca, valor) values (3, 'Processador', 'Colorful', 5083.31);
insert into produto (idProduto, nome, marca, valor) values (4, 'Notebook', 'Zadak', 10584.16);
insert into produto (idProduto, nome, marca, valor) values (5, 'Processador', 'Asrock', 13880.39);
insert into produto (idProduto, nome, marca, valor) values (6, 'Placa de som', 'Colorful', 8954.77);
insert into produto (idProduto, nome, marca, valor) values (7, 'Placa de Video', 'Asrock', 5507.04);
insert into produto (idProduto, nome, marca, valor) values (8, 'Placa de som', 'Evga', 4445.44);
insert into produto (idProduto, nome, marca, valor) values (9, 'Headset', 'Colorful', 13722.72);
insert into produto (idProduto, nome, marca, valor) values (10, 'Memória RAM', 'Biostar', 5650.09);
insert into produto (idProduto, nome, marca, valor) values (11, 'SSD', 'MSI', 1934.83);
insert into produto (idProduto, nome, marca, valor) values (12, 'SSD', 'Asrock', 6216.04);
insert into produto (idProduto, nome, marca, valor) values (13, 'Gabinete', 'Gigabyte', 12858.81);
insert into produto (idProduto, nome, marca, valor) values (14, 'Thermal Pad', 'Zadak', 9186.0);
insert into produto (idProduto, nome, marca, valor) values (15, 'Notebook', 'Gigabyte', 2004.09);
insert into produto (idProduto, nome, marca, valor) values (16, 'Placa de Video', 'G.Skill', 6406.31);
insert into produto (idProduto, nome, marca, valor) values (17, 'Placa de Video', 'MSI', 10452.71);
insert into produto (idProduto, nome, marca, valor) values (18, 'Fonte', 'Gigabyte', 313.38);
insert into produto (idProduto, nome, marca, valor) values (19, 'Mousepad', 'Lian Li', 12550.41);
insert into produto (idProduto, nome, marca, valor) values (20, 'HD', 'Colorful', 425.96);
insert into produto (idProduto, nome, marca, valor) values (21, 'Placa de som', 'G.Skill', 5063.95);
insert into produto (idProduto, nome, marca, valor) values (22, 'Monitor', 'MSI', 8211.91);
insert into produto (idProduto, nome, marca, valor) values (23, 'Notebook', 'Gigabyte', 9605.14);
insert into produto (idProduto, nome, marca, valor) values (24, 'Pasta Térmica', 'Lian Li', 6677.31);
insert into produto (idProduto, nome, marca, valor) values (25, 'Placa de som', 'Powercolor', 6397.77);
insert into produto (idProduto, nome, marca, valor) values (26, 'Monitor', 'Gigabyte', 13719.17);
insert into produto (idProduto, nome, marca, valor) values (27, 'Processador', 'Gigabyte', 135.71);
insert into produto (idProduto, nome, marca, valor) values (28, 'Monitor', 'Lian Li', 10675.73);
insert into produto (idProduto, nome, marca, valor) values (29, 'Gabinete', 'Gigabyte', 8865.02);
insert into produto (idProduto, nome, marca, valor) values (30, 'Teclado', 'Asus', 14298.65);
insert into produto (idProduto, nome, marca, valor) values (31, 'Pasta Térmica', 'Powercolor', 14575.43);
insert into produto (idProduto, nome, marca, valor) values (32, 'Pasta Térmica', 'Powercolor', 13780.96);
insert into produto (idProduto, nome, marca, valor) values (33, 'Placa de Video', 'Asus', 446.96);
insert into produto (idProduto, nome, marca, valor) values (34, 'CPU Cooler', 'Asus', 3628.21);
insert into produto (idProduto, nome, marca, valor) values (35, 'Processador', 'G.Skill', 10605.11);
insert into produto (idProduto, nome, marca, valor) values (36, 'Monitor', 'Biostar', 10102.71);
insert into produto (idProduto, nome, marca, valor) values (37, 'Placa de som', 'Vinik', 4528.3);
insert into produto (idProduto, nome, marca, valor) values (38, 'Placa de rede', 'Lian Li', 14664.26);
insert into produto (idProduto, nome, marca, valor) values (39, 'Monitor', 'Biostar', 9665.16);
insert into produto (idProduto, nome, marca, valor) values (40, 'Mouse', 'MSI', 5608.67);
insert into produto (idProduto, nome, marca, valor) values (41, 'Placa de som', 'G.Skill', 14627.86);
insert into produto (idProduto, nome, marca, valor) values (42, 'CPU Cooler', 'Lian Li', 5235.47);
insert into produto (idProduto, nome, marca, valor) values (43, 'Placa de som', 'Asus', 14440.5);
insert into produto (idProduto, nome, marca, valor) values (44, 'Processador', 'Zadak', 2444.21);
insert into produto (idProduto, nome, marca, valor) values (45, 'CPU Cooler', 'Zadak', 14237.24);
insert into produto (idProduto, nome, marca, valor) values (46, 'Placa de rede', 'Gigabyte', 2734.38);
insert into produto (idProduto, nome, marca, valor) values (47, 'Placa de Video', 'Gigabyte', 4322.0);
insert into produto (idProduto, nome, marca, valor) values (48, 'CPU Cooler', 'Powercolor', 12485.13);
insert into produto (idProduto, nome, marca, valor) values (49, 'SSD', 'MSI', 13286.14);
insert into produto (idProduto, nome, marca, valor) values (50, 'Thermal Pad', 'Asrock', 10384.86);
insert into produto (idProduto, nome, marca, valor) values (51, 'Memória RAM', 'Powercolor', 4174.58);
insert into produto (idProduto, nome, marca, valor) values (52, 'Notebook', 'MSI', 10220.14);
insert into produto (idProduto, nome, marca, valor) values (53, 'Mousepad', 'Powercolor', 6650.69);
insert into produto (idProduto, nome, marca, valor) values (54, 'CPU Cooler', 'Evga', 6857.31);
insert into produto (idProduto, nome, marca, valor) values (55, 'Placa-mãe', 'MSI', 1996.76);
insert into produto (idProduto, nome, marca, valor) values (56, 'Placa-mãe', 'Colorful', 6053.25);
insert into produto (idProduto, nome, marca, valor) values (57, 'CPU Cooler', 'Gigabyte', 3408.34);
insert into produto (idProduto, nome, marca, valor) values (58, 'Fonte', 'Vinik', 11044.69);
insert into produto (idProduto, nome, marca, valor) values (59, 'Placa de Video', 'Gigabyte', 13657.17);
insert into produto (idProduto, nome, marca, valor) values (60, 'Placa de som', 'Powercolor', 6833.95);
insert into produto (idProduto, nome, marca, valor) values (61, 'Pasta Térmica', 'Asus', 14549.81);
insert into produto (idProduto, nome, marca, valor) values (62, 'Placa de som', 'Zadak', 13226.04);
insert into produto (idProduto, nome, marca, valor) values (63, 'Memória RAM', 'Lian Li', 617.78);
insert into produto (idProduto, nome, marca, valor) values (64, 'Placa de som', 'Evga', 5.21);
insert into produto (idProduto, nome, marca, valor) values (65, 'Placa de som', 'Lian Li', 9689.73);
insert into produto (idProduto, nome, marca, valor) values (66, 'Placa-mãe', 'Evga', 12800.37);
insert into produto (idProduto, nome, marca, valor) values (67, 'Memória RAM', 'Biostar', 6021.62);
insert into produto (idProduto, nome, marca, valor) values (68, 'Fonte', 'Evga', 14978.97);
insert into produto (idProduto, nome, marca, valor) values (69, 'Placa de rede', 'Powercolor', 13426.59);
insert into produto (idProduto, nome, marca, valor) values (70, 'HD', 'Colorful', 11780.98);
insert into produto (idProduto, nome, marca, valor) values (71, 'Headset', 'MSI', 7896.06);
insert into produto (idProduto, nome, marca, valor) values (72, 'CPU Cooler', 'Biostar', 13087.67);
insert into produto (idProduto, nome, marca, valor) values (73, 'Gabinete', 'MSI', 2753.1);
insert into produto (idProduto, nome, marca, valor) values (74, 'SSD', 'Colorful', 10572.71);
insert into produto (idProduto, nome, marca, valor) values (75, 'Memória RAM', 'MSI', 5450.07);
insert into produto (idProduto, nome, marca, valor) values (76, 'Mouse', 'Biostar', 1890.78);
insert into produto (idProduto, nome, marca, valor) values (77, 'Pasta Térmica', 'G.Skill', 7751.25);
insert into produto (idProduto, nome, marca, valor) values (78, 'Teclado', 'Gigabyte', 10146.44);
insert into produto (idProduto, nome, marca, valor) values (79, 'Placa de som', 'Vinik', 2935.04);
insert into produto (idProduto, nome, marca, valor) values (80, 'Processador', 'G.Skill', 12727.9);
insert into produto (idProduto, nome, marca, valor) values (81, 'Teclado', 'MSI', 11472.44);
insert into produto (idProduto, nome, marca, valor) values (82, 'Placa-mãe', 'Biostar', 3071.38);
insert into produto (idProduto, nome, marca, valor) values (83, 'Headset', 'Asrock', 13096.98);
insert into produto (idProduto, nome, marca, valor) values (84, 'Monitor', 'Vinik', 2540.89);
insert into produto (idProduto, nome, marca, valor) values (85, 'Headset', 'Gigabyte', 4045.92);
insert into produto (idProduto, nome, marca, valor) values (86, 'CPU Cooler', 'G.Skill', 10684.65);
insert into produto (idProduto, nome, marca, valor) values (87, 'Pasta Térmica', 'Asus', 12583.25);
insert into produto (idProduto, nome, marca, valor) values (88, 'Notebook', 'G.Skill', 2567.93);
insert into produto (idProduto, nome, marca, valor) values (89, 'Pasta Térmica', 'MSI', 8764.74);
insert into produto (idProduto, nome, marca, valor) values (90, 'Placa de Video', 'Powercolor', 5585.03);
insert into produto (idProduto, nome, marca, valor) values (91, 'Processador', 'Gigabyte', 4175.14);
insert into produto (idProduto, nome, marca, valor) values (92, 'Mouse', 'Gigabyte', 4061.53);
insert into produto (idProduto, nome, marca, valor) values (93, 'Mouse', 'Lian Li', 5008.46);
insert into produto (idProduto, nome, marca, valor) values (94, 'Thermal Pad', 'Colorful', 10562.5);
insert into produto (idProduto, nome, marca, valor) values (95, 'Gabinete', 'Lian Li', 6586.35);
insert into produto (idProduto, nome, marca, valor) values (96, 'HD', 'Asrock', 8470.43);
insert into produto (idProduto, nome, marca, valor) values (97, 'Placa de Video', 'Zadak', 10049.47);
insert into produto (idProduto, nome, marca, valor) values (98, 'Fonte', 'Asrock', 2227.25);
insert into produto (idProduto, nome, marca, valor) values (99, 'Mousepad', 'MSI', 11940.38);
insert into produto (idProduto, nome, marca, valor) values (100, 'Memória RAM', 'Evga', 11283.86);
insert into produto (idProduto, nome, marca, valor) values (101, 'Placa-mãe', 'Gigabyte', 7121.7);
insert into produto (idProduto, nome, marca, valor) values (102, 'Notebook', 'Zadak', 2680.53);
insert into produto (idProduto, nome, marca, valor) values (103, 'Fonte', 'Asus', 2403.91);
insert into produto (idProduto, nome, marca, valor) values (104, 'Teclado', 'G.Skill', 9808.38);
insert into produto (idProduto, nome, marca, valor) values (105, 'Processador', 'Asrock', 4998.49);
insert into produto (idProduto, nome, marca, valor) values (106, 'Placa de rede', 'MSI', 9515.57);
insert into produto (idProduto, nome, marca, valor) values (107, 'Processador', 'Colorful', 14082.46);
insert into produto (idProduto, nome, marca, valor) values (108, 'Mouse', 'MSI', 4617.55);
insert into produto (idProduto, nome, marca, valor) values (109, 'Fonte', 'Colorful', 12035.56);
insert into produto (idProduto, nome, marca, valor) values (110, 'Thermal Pad', 'Asrock', 1188.29);
insert into produto (idProduto, nome, marca, valor) values (111, 'Fonte', 'Asrock', 8552.47);
insert into produto (idProduto, nome, marca, valor) values (112, 'Processador', 'Lian Li', 5423.73);
insert into produto (idProduto, nome, marca, valor) values (113, 'Notebook', 'Vinik', 8395.75);
insert into produto (idProduto, nome, marca, valor) values (114, 'Monitor', 'Evga', 8919.93);
insert into produto (idProduto, nome, marca, valor) values (115, 'Monitor', 'Lian Li', 9364.91);
insert into produto (idProduto, nome, marca, valor) values (116, 'Processador', 'MSI', 8654.66);
insert into produto (idProduto, nome, marca, valor) values (117, 'Thermal Pad', 'Colorful', 3434.5);
insert into produto (idProduto, nome, marca, valor) values (118, 'Pasta Térmica', 'Asrock', 993.34);
insert into produto (idProduto, nome, marca, valor) values (119, 'Mouse', 'Asus', 7727.46);
insert into produto (idProduto, nome, marca, valor) values (120, 'Placa de Video', 'Vinik', 6101.7);
insert into produto (idProduto, nome, marca, valor) values (121, 'Mousepad', 'Powercolor', 645.54);
insert into produto (idProduto, nome, marca, valor) values (122, 'CPU Cooler', 'Gigabyte', 2057.96);
insert into produto (idProduto, nome, marca, valor) values (123, 'Placa de som', 'Asus', 1922.45);
insert into produto (idProduto, nome, marca, valor) values (124, 'Mousepad', 'Gigabyte', 2892.57);
insert into produto (idProduto, nome, marca, valor) values (125, 'Fonte', 'Lian Li', 9367.67);
insert into produto (idProduto, nome, marca, valor) values (126, 'SSD', 'Evga', 1620.55);
insert into produto (idProduto, nome, marca, valor) values (127, 'Gabinete', 'Lian Li', 2303.09);
insert into produto (idProduto, nome, marca, valor) values (128, 'Processador', 'Powercolor', 2228.96);
insert into produto (idProduto, nome, marca, valor) values (129, 'Fonte', 'Gigabyte', 5786.31);
insert into produto (idProduto, nome, marca, valor) values (130, 'SSD', 'Colorful', 7217.82);
insert into produto (idProduto, nome, marca, valor) values (131, 'Mouse', 'Evga', 3683.06);
insert into produto (idProduto, nome, marca, valor) values (132, 'Headset', 'Vinik', 14048.05);
insert into produto (idProduto, nome, marca, valor) values (133, 'Memória RAM', 'Lian Li', 303.69);
insert into produto (idProduto, nome, marca, valor) values (134, 'Processador', 'MSI', 4763.47);
insert into produto (idProduto, nome, marca, valor) values (135, 'Fonte', 'G.Skill', 2683.92);
insert into produto (idProduto, nome, marca, valor) values (136, 'Gabinete', 'Lian Li', 7842.87);
insert into produto (idProduto, nome, marca, valor) values (137, 'Teclado', 'Vinik', 1318.81);
insert into produto (idProduto, nome, marca, valor) values (138, 'SSD', 'G.Skill', 12894.54);
insert into produto (idProduto, nome, marca, valor) values (139, 'Teclado', 'MSI', 4056.22);
insert into produto (idProduto, nome, marca, valor) values (140, 'Pasta Térmica', 'Asrock', 6834.27);
insert into produto (idProduto, nome, marca, valor) values (141, 'Placa de Video', 'G.Skill', 4307.28);
insert into produto (idProduto, nome, marca, valor) values (142, 'Notebook', 'Asrock', 8800.36);
insert into produto (idProduto, nome, marca, valor) values (143, 'Notebook', 'Asrock', 5980.64);
insert into produto (idProduto, nome, marca, valor) values (144, 'Thermal Pad', 'Asrock', 10169.56);
insert into produto (idProduto, nome, marca, valor) values (145, 'Pasta Térmica', 'Gigabyte', 2311.3);
insert into produto (idProduto, nome, marca, valor) values (146, 'Monitor', 'Lian Li', 1229.03);
insert into produto (idProduto, nome, marca, valor) values (147, 'Placa-mãe', 'Evga', 8094.06);
insert into produto (idProduto, nome, marca, valor) values (148, 'Memória RAM', 'Evga', 6165.26);
insert into produto (idProduto, nome, marca, valor) values (149, 'Processador', 'MSI', 9417.22);
insert into produto (idProduto, nome, marca, valor) values (150, 'Pasta Térmica', 'Biostar', 13580.5);
insert into produto (idProduto, nome, marca, valor) values (151, 'Headset', 'Colorful', 8833.97);
insert into produto (idProduto, nome, marca, valor) values (152, 'Notebook', 'Biostar', 1139.44);
insert into produto (idProduto, nome, marca, valor) values (153, 'Placa de rede', 'Asus', 7591.66);
insert into produto (idProduto, nome, marca, valor) values (154, 'Mouse', 'Asrock', 9959.3);
insert into produto (idProduto, nome, marca, valor) values (155, 'Pasta Térmica', 'Gigabyte', 11423.54);
insert into produto (idProduto, nome, marca, valor) values (156, 'Mouse', 'G.Skill', 12878.13);
insert into produto (idProduto, nome, marca, valor) values (157, 'Pasta Térmica', 'Asrock', 1124.95);
insert into produto (idProduto, nome, marca, valor) values (158, 'Placa de rede', 'Vinik', 10183.41);
insert into produto (idProduto, nome, marca, valor) values (159, 'HD', 'Asrock', 1428.91);
insert into produto (idProduto, nome, marca, valor) values (160, 'Fonte', 'Evga', 9162.54);
insert into produto (idProduto, nome, marca, valor) values (161, 'Teclado', 'Biostar', 14767.39);
insert into produto (idProduto, nome, marca, valor) values (162, 'Mousepad', 'Asrock', 8135.77);
insert into produto (idProduto, nome, marca, valor) values (163, 'Pasta Térmica', 'Asus', 9723.21);
insert into produto (idProduto, nome, marca, valor) values (164, 'Placa de Video', 'MSI', 8825.68);
insert into produto (idProduto, nome, marca, valor) values (165, 'Placa de rede', 'Asus', 3159.37);
insert into produto (idProduto, nome, marca, valor) values (166, 'Mousepad', 'Gigabyte', 11133.73);
insert into produto (idProduto, nome, marca, valor) values (167, 'Notebook', 'Lian Li', 8383.87);
insert into produto (idProduto, nome, marca, valor) values (168, 'HD', 'Asus', 13503.21);
insert into produto (idProduto, nome, marca, valor) values (169, 'Gabinete', 'Asrock', 1104.24);
insert into produto (idProduto, nome, marca, valor) values (170, 'Thermal Pad', 'Zadak', 4539.49);
insert into produto (idProduto, nome, marca, valor) values (171, 'Gabinete', 'Zadak', 13891.97);
insert into produto (idProduto, nome, marca, valor) values (172, 'Teclado', 'Vinik', 3219.72);
insert into produto (idProduto, nome, marca, valor) values (173, 'Processador', 'G.Skill', 2594.52);
insert into produto (idProduto, nome, marca, valor) values (174, 'Notebook', 'Colorful', 2323.29);
insert into produto (idProduto, nome, marca, valor) values (175, 'Placa de som', 'MSI', 8251.64);
insert into produto (idProduto, nome, marca, valor) values (176, 'Mouse', 'Lian Li', 2121.57);
insert into produto (idProduto, nome, marca, valor) values (177, 'Processador', 'Colorful', 12514.02);
insert into produto (idProduto, nome, marca, valor) values (178, 'Placa-mãe', 'Evga', 12675.89);
insert into produto (idProduto, nome, marca, valor) values (179, 'SSD', 'G.Skill', 10530.03);
insert into produto (idProduto, nome, marca, valor) values (180, 'Memória RAM', 'Zadak', 1900.69);
insert into produto (idProduto, nome, marca, valor) values (181, 'Placa de som', 'Powercolor', 3647.07);
insert into produto (idProduto, nome, marca, valor) values (182, 'Placa de Video', 'Vinik', 8911.98);
insert into produto (idProduto, nome, marca, valor) values (183, 'Mouse', 'Asrock', 5174.32);
insert into produto (idProduto, nome, marca, valor) values (184, 'SSD', 'Evga', 14301.48);
insert into produto (idProduto, nome, marca, valor) values (185, 'SSD', 'Vinik', 7081.39);
insert into produto (idProduto, nome, marca, valor) values (186, 'Monitor', 'Lian Li', 13146.8);
insert into produto (idProduto, nome, marca, valor) values (187, 'SSD', 'MSI', 13151.13);
insert into produto (idProduto, nome, marca, valor) values (188, 'Memória RAM', 'Asus', 13928.54);
insert into produto (idProduto, nome, marca, valor) values (189, 'Placa de som', 'Asrock', 6150.61);
insert into produto (idProduto, nome, marca, valor) values (190, 'Thermal Pad', 'G.Skill', 14769.2);
insert into produto (idProduto, nome, marca, valor) values (191, 'Notebook', 'Biostar', 4582.32);
insert into produto (idProduto, nome, marca, valor) values (192, 'Placa de som', 'G.Skill', 14174.32);
insert into produto (idProduto, nome, marca, valor) values (193, 'Mouse', 'Vinik', 5202.3);
insert into produto (idProduto, nome, marca, valor) values (194, 'Mousepad', 'Evga', 12613.52);
insert into produto (idProduto, nome, marca, valor) values (195, 'Monitor', 'Colorful', 253.84);
insert into produto (idProduto, nome, marca, valor) values (196, 'CPU Cooler', 'Lian Li', 12122.19);
insert into produto (idProduto, nome, marca, valor) values (197, 'Gabinete', 'Biostar', 3548.29);
insert into produto (idProduto, nome, marca, valor) values (198, 'Placa-mãe', 'Gigabyte', 5728.07);
insert into produto (idProduto, nome, marca, valor) values (199, 'Mouse', 'Asrock', 1386.64);
insert into produto (idProduto, nome, marca, valor) values (200, 'Pasta Térmica', 'Zadak', 6838.69);
insert into produto (idProduto, nome, marca, valor) values (201, 'Mouse', 'Lian Li', 8952.28);
insert into produto (idProduto, nome, marca, valor) values (202, 'HD', 'Biostar', 9763.93);
insert into produto (idProduto, nome, marca, valor) values (203, 'Fonte', 'Zadak', 1420.11);
insert into produto (idProduto, nome, marca, valor) values (204, 'Placa de Video', 'Vinik', 13487.29);
insert into produto (idProduto, nome, marca, valor) values (205, 'Placa de rede', 'Gigabyte', 8685.29);
insert into produto (idProduto, nome, marca, valor) values (206, 'Notebook', 'Asrock', 14690.08);
insert into produto (idProduto, nome, marca, valor) values (207, 'Gabinete', 'Vinik', 10543.52);
insert into produto (idProduto, nome, marca, valor) values (208, 'Monitor', 'Lian Li', 923.92);
insert into produto (idProduto, nome, marca, valor) values (209, 'Fonte', 'Gigabyte', 11055.94);
insert into produto (idProduto, nome, marca, valor) values (210, 'HD', 'Asus', 8287.4);
insert into produto (idProduto, nome, marca, valor) values (211, 'Mouse', 'Colorful', 8023.92);
insert into produto (idProduto, nome, marca, valor) values (212, 'CPU Cooler', 'MSI', 6171.39);
insert into produto (idProduto, nome, marca, valor) values (213, 'Processador', 'Colorful', 5903.11);
insert into produto (idProduto, nome, marca, valor) values (214, 'Headset', 'Evga', 8351.63);
insert into produto (idProduto, nome, marca, valor) values (215, 'Teclado', 'Zadak', 3472.61);
insert into produto (idProduto, nome, marca, valor) values (216, 'Monitor', 'Evga', 5856.89);
insert into produto (idProduto, nome, marca, valor) values (217, 'Gabinete', 'Asus', 12561.87);
insert into produto (idProduto, nome, marca, valor) values (218, 'Notebook', 'Lian Li', 12387.26);
insert into produto (idProduto, nome, marca, valor) values (219, 'Teclado', 'Gigabyte', 486.56);
insert into produto (idProduto, nome, marca, valor) values (220, 'Thermal Pad', 'Zadak', 10936.22);
insert into produto (idProduto, nome, marca, valor) values (221, 'Pasta Térmica', 'Colorful', 1037.66);
insert into produto (idProduto, nome, marca, valor) values (222, 'Mouse', 'Gigabyte', 6805.88);
insert into produto (idProduto, nome, marca, valor) values (223, 'Placa de Video', 'Zadak', 1298.35);
insert into produto (idProduto, nome, marca, valor) values (224, 'Placa-mãe', 'Powercolor', 6701.22);
insert into produto (idProduto, nome, marca, valor) values (225, 'Headset', 'Evga', 7676.36);
insert into produto (idProduto, nome, marca, valor) values (226, 'Processador', 'Lian Li', 7723.93);
insert into produto (idProduto, nome, marca, valor) values (227, 'Gabinete', 'Asrock', 495.23);
insert into produto (idProduto, nome, marca, valor) values (228, 'CPU Cooler', 'Asus', 2336.25);
insert into produto (idProduto, nome, marca, valor) values (229, 'Mousepad', 'Gigabyte', 13980.93);
insert into produto (idProduto, nome, marca, valor) values (230, 'Gabinete', 'Biostar', 7665.18);
insert into produto (idProduto, nome, marca, valor) values (231, 'Thermal Pad', 'Vinik', 4639.73);
insert into produto (idProduto, nome, marca, valor) values (232, 'Placa de rede', 'MSI', 14712.91);
insert into produto (idProduto, nome, marca, valor) values (233, 'HD', 'Asus', 12274.62);
insert into produto (idProduto, nome, marca, valor) values (234, 'Placa de rede', 'Gigabyte', 11416.92);
insert into produto (idProduto, nome, marca, valor) values (235, 'Thermal Pad', 'Powercolor', 4853.56);
insert into produto (idProduto, nome, marca, valor) values (236, 'Processador', 'Biostar', 4838.53);
insert into produto (idProduto, nome, marca, valor) values (237, 'Placa-mãe', 'Vinik', 8045.28);
insert into produto (idProduto, nome, marca, valor) values (238, 'Notebook', 'Colorful', 3101.36);
insert into produto (idProduto, nome, marca, valor) values (239, 'Monitor', 'Evga', 9960.77);
insert into produto (idProduto, nome, marca, valor) values (240, 'SSD', 'Biostar', 10910.62);
insert into produto (idProduto, nome, marca, valor) values (241, 'Headset', 'Asrock', 354.24);
insert into produto (idProduto, nome, marca, valor) values (242, 'Processador', 'Asrock', 11130.29);
insert into produto (idProduto, nome, marca, valor) values (243, 'Fonte', 'Asus', 3910.87);
insert into produto (idProduto, nome, marca, valor) values (244, 'Pasta Térmica', 'Biostar', 6481.97);
insert into produto (idProduto, nome, marca, valor) values (245, 'Headset', 'Asrock', 11745.94);
insert into produto (idProduto, nome, marca, valor) values (246, 'Placa-mãe', 'Gigabyte', 8554.82);
insert into produto (idProduto, nome, marca, valor) values (247, 'SSD', 'Evga', 11353.78);
insert into produto (idProduto, nome, marca, valor) values (248, 'Placa de rede', 'Colorful', 400.44);
insert into produto (idProduto, nome, marca, valor) values (249, 'CPU Cooler', 'Asrock', 2982.54);
insert into produto (idProduto, nome, marca, valor) values (250, 'Fonte', 'Colorful', 1766.87);
insert into produto (idProduto, nome, marca, valor) values (251, 'Thermal Pad', 'Biostar', 4387.67);
insert into produto (idProduto, nome, marca, valor) values (252, 'Notebook', 'Asus', 13756.24);
insert into produto (idProduto, nome, marca, valor) values (253, 'Placa de Video', 'Powercolor', 9911.27);
insert into produto (idProduto, nome, marca, valor) values (254, 'Processador', 'Vinik', 12767.69);
insert into produto (idProduto, nome, marca, valor) values (255, 'Pasta Térmica', 'Zadak', 7468.22);
insert into produto (idProduto, nome, marca, valor) values (256, 'Placa de rede', 'Asrock', 5941.89);
insert into produto (idProduto, nome, marca, valor) values (257, 'Teclado', 'Lian Li', 4131.83);
insert into produto (idProduto, nome, marca, valor) values (258, 'Mouse', 'G.Skill', 2589.43);
insert into produto (idProduto, nome, marca, valor) values (259, 'Mousepad', 'Vinik', 11433.79);
insert into produto (idProduto, nome, marca, valor) values (260, 'SSD', 'Vinik', 6971.99);
insert into produto (idProduto, nome, marca, valor) values (261, 'Notebook', 'Asrock', 8656.36);
insert into produto (idProduto, nome, marca, valor) values (262, 'CPU Cooler', 'Gigabyte', 7977.77);
insert into produto (idProduto, nome, marca, valor) values (263, 'Notebook', 'Gigabyte', 6648.71);
insert into produto (idProduto, nome, marca, valor) values (264, 'Memória RAM', 'G.Skill', 7337.43);
insert into produto (idProduto, nome, marca, valor) values (265, 'Headset', 'Colorful', 12580.27);
insert into produto (idProduto, nome, marca, valor) values (266, 'Placa de rede', 'Powercolor', 4941.85);
insert into produto (idProduto, nome, marca, valor) values (267, 'Notebook', 'Lian Li', 3446.91);
insert into produto (idProduto, nome, marca, valor) values (268, 'Teclado', 'Asrock', 8479.37);
insert into produto (idProduto, nome, marca, valor) values (269, 'Thermal Pad', 'Evga', 4558.6);
insert into produto (idProduto, nome, marca, valor) values (270, 'Teclado', 'Powercolor', 5248.08);
insert into produto (idProduto, nome, marca, valor) values (271, 'Headset', 'Vinik', 4307.01);
insert into produto (idProduto, nome, marca, valor) values (272, 'Mousepad', 'Zadak', 4857.61);
insert into produto (idProduto, nome, marca, valor) values (273, 'Notebook', 'G.Skill', 8961.03);
insert into produto (idProduto, nome, marca, valor) values (274, 'Mouse', 'Powercolor', 11288.09);
insert into produto (idProduto, nome, marca, valor) values (275, 'Placa-mãe', 'Gigabyte', 6105.47);
insert into produto (idProduto, nome, marca, valor) values (276, 'Mouse', 'Vinik', 3367.44);
insert into produto (idProduto, nome, marca, valor) values (277, 'Teclado', 'Biostar', 8676.67);
insert into produto (idProduto, nome, marca, valor) values (278, 'Placa de Video', 'Lian Li', 1079.2);
insert into produto (idProduto, nome, marca, valor) values (279, 'Gabinete', 'G.Skill', 12226.47);
insert into produto (idProduto, nome, marca, valor) values (280, 'Placa de som', 'Colorful', 5147.64);
insert into produto (idProduto, nome, marca, valor) values (281, 'Processador', 'Asus', 6449.24);
insert into produto (idProduto, nome, marca, valor) values (282, 'Teclado', 'Evga', 14480.02);
insert into produto (idProduto, nome, marca, valor) values (283, 'Placa de rede', 'Evga', 6262.94);
insert into produto (idProduto, nome, marca, valor) values (284, 'SSD', 'Asrock', 7157.77);
insert into produto (idProduto, nome, marca, valor) values (285, 'Placa-mãe', 'Colorful', 9393.94);
insert into produto (idProduto, nome, marca, valor) values (286, 'Pasta Térmica', 'Evga', 4551.42);
insert into produto (idProduto, nome, marca, valor) values (287, 'Gabinete', 'Zadak', 2784.44);
insert into produto (idProduto, nome, marca, valor) values (288, 'Notebook', 'Evga', 1994.51);
insert into produto (idProduto, nome, marca, valor) values (289, 'HD', 'Gigabyte', 4738.05);
insert into produto (idProduto, nome, marca, valor) values (290, 'Placa de som', 'MSI', 9339.48);
insert into produto (idProduto, nome, marca, valor) values (291, 'HD', 'Asrock', 4610.74);
insert into produto (idProduto, nome, marca, valor) values (292, 'Placa de rede', 'Biostar', 6358.57);
insert into produto (idProduto, nome, marca, valor) values (293, 'Memória RAM', 'Gigabyte', 7623.78);
insert into produto (idProduto, nome, marca, valor) values (294, 'Thermal Pad', 'Vinik', 4662.95);
insert into produto (idProduto, nome, marca, valor) values (295, 'Mousepad', 'Evga', 12349.26);
insert into produto (idProduto, nome, marca, valor) values (296, 'Monitor', 'MSI', 7310.45);
insert into produto (idProduto, nome, marca, valor) values (297, 'Fonte', 'Asus', 6093.6);
insert into produto (idProduto, nome, marca, valor) values (298, 'SSD', 'Lian Li', 13117.89);
insert into produto (idProduto, nome, marca, valor) values (299, 'Placa-mãe', 'Vinik', 2878.95);
insert into produto (idProduto, nome, marca, valor) values (300, 'Memória RAM', 'Gigabyte', 656.03);
insert into produto (idProduto, nome, marca, valor) values (301, 'Mousepad', 'G.Skill', 8468.07);
insert into produto (idProduto, nome, marca, valor) values (302, 'Memória RAM', 'MSI', 489.41);
insert into produto (idProduto, nome, marca, valor) values (303, 'Memória RAM', 'Gigabyte', 7115.61);
insert into produto (idProduto, nome, marca, valor) values (304, 'Mousepad', 'Powercolor', 4809.78);
insert into produto (idProduto, nome, marca, valor) values (305, 'Notebook', 'Evga', 6991.87);
insert into produto (idProduto, nome, marca, valor) values (306, 'Headset', 'Vinik', 12444.32);
insert into produto (idProduto, nome, marca, valor) values (307, 'HD', 'Zadak', 3562.11);
insert into produto (idProduto, nome, marca, valor) values (308, 'Placa de rede', 'Biostar', 10078.03);
insert into produto (idProduto, nome, marca, valor) values (309, 'Placa-mãe', 'Zadak', 3248.09);
insert into produto (idProduto, nome, marca, valor) values (310, 'Fonte', 'Biostar', 10041.76);
insert into produto (idProduto, nome, marca, valor) values (311, 'Pasta Térmica', 'Powercolor', 12079.11);
insert into produto (idProduto, nome, marca, valor) values (312, 'Memória RAM', 'Evga', 3097.8);
insert into produto (idProduto, nome, marca, valor) values (313, 'Placa de Video', 'Asrock', 13187.29);
insert into produto (idProduto, nome, marca, valor) values (314, 'Monitor', 'Biostar', 13322.35);
insert into produto (idProduto, nome, marca, valor) values (315, 'Placa de Video', 'Evga', 9984.62);
insert into produto (idProduto, nome, marca, valor) values (316, 'Placa de Video', 'G.Skill', 6512.76);
insert into produto (idProduto, nome, marca, valor) values (317, 'CPU Cooler', 'Biostar', 2160.6);
insert into produto (idProduto, nome, marca, valor) values (318, 'Processador', 'Zadak', 7283.55);
insert into produto (idProduto, nome, marca, valor) values (319, 'Memória RAM', 'Gigabyte', 5317.34);
insert into produto (idProduto, nome, marca, valor) values (320, 'Placa de rede', 'Powercolor', 3373.79);
insert into produto (idProduto, nome, marca, valor) values (321, 'Teclado', 'Gigabyte', 2189.15);
insert into produto (idProduto, nome, marca, valor) values (322, 'Thermal Pad', 'Vinik', 4329.09);
insert into produto (idProduto, nome, marca, valor) values (323, 'Teclado', 'Gigabyte', 12735.6);
insert into produto (idProduto, nome, marca, valor) values (324, 'Fonte', 'Evga', 4501.88);
insert into produto (idProduto, nome, marca, valor) values (325, 'Gabinete', 'Asus', 729.34);
insert into produto (idProduto, nome, marca, valor) values (326, 'Processador', 'Asrock', 3104.1);
insert into produto (idProduto, nome, marca, valor) values (327, 'Placa de Video', 'Colorful', 2755.86);
insert into produto (idProduto, nome, marca, valor) values (328, 'Gabinete', 'Gigabyte', 5456.73);
insert into produto (idProduto, nome, marca, valor) values (329, 'Gabinete', 'G.Skill', 8705.89);
insert into produto (idProduto, nome, marca, valor) values (330, 'Processador', 'Asus', 7633.95);
insert into produto (idProduto, nome, marca, valor) values (331, 'Processador', 'Asrock', 6168.68);
insert into produto (idProduto, nome, marca, valor) values (332, 'CPU Cooler', 'MSI', 5750.66);
insert into produto (idProduto, nome, marca, valor) values (333, 'Headset', 'MSI', 488.57);
insert into produto (idProduto, nome, marca, valor) values (334, 'Fonte', 'Asrock', 7258.64);
insert into produto (idProduto, nome, marca, valor) values (335, 'SSD', 'Asrock', 8157.65);
insert into produto (idProduto, nome, marca, valor) values (336, 'Placa de som', 'Vinik', 13030.6);
insert into produto (idProduto, nome, marca, valor) values (337, 'HD', 'Colorful', 1970.8);
insert into produto (idProduto, nome, marca, valor) values (338, 'Placa de som', 'Evga', 11224.42);
insert into produto (idProduto, nome, marca, valor) values (339, 'Placa de Video', 'Vinik', 9525.39);
insert into produto (idProduto, nome, marca, valor) values (340, 'Gabinete', 'Gigabyte', 3025.91);
insert into produto (idProduto, nome, marca, valor) values (341, 'Gabinete', 'Gigabyte', 10122.97);
insert into produto (idProduto, nome, marca, valor) values (342, 'Thermal Pad', 'Colorful', 5518.26);
insert into produto (idProduto, nome, marca, valor) values (343, 'CPU Cooler', 'Evga', 2166.58);
insert into produto (idProduto, nome, marca, valor) values (344, 'Headset', 'Zadak', 8612.13);
insert into produto (idProduto, nome, marca, valor) values (345, 'Mouse', 'MSI', 5295.01);
insert into produto (idProduto, nome, marca, valor) values (346, 'SSD', 'Asus', 1172.72);
insert into produto (idProduto, nome, marca, valor) values (347, 'Mousepad', 'Lian Li', 1152.21);
insert into produto (idProduto, nome, marca, valor) values (348, 'Placa de som', 'Asus', 13549.9);
insert into produto (idProduto, nome, marca, valor) values (349, 'Placa de som', 'G.Skill', 6441.65);
insert into produto (idProduto, nome, marca, valor) values (350, 'Notebook', 'Evga', 11481.06);
insert into produto (idProduto, nome, marca, valor) values (351, 'Teclado', 'Colorful', 7512.37);
insert into produto (idProduto, nome, marca, valor) values (352, 'Mousepad', 'Gigabyte', 11639.65);
insert into produto (idProduto, nome, marca, valor) values (353, 'Placa de som', 'MSI', 12826.05);
insert into produto (idProduto, nome, marca, valor) values (354, 'Teclado', 'Colorful', 7225.78);
insert into produto (idProduto, nome, marca, valor) values (355, 'Placa-mãe', 'Asrock', 14473.82);
insert into produto (idProduto, nome, marca, valor) values (356, 'Memória RAM', 'MSI', 32.96);
insert into produto (idProduto, nome, marca, valor) values (357, 'Processador', 'MSI', 12383.7);
insert into produto (idProduto, nome, marca, valor) values (358, 'Mousepad', 'Asus', 2576.24);
insert into produto (idProduto, nome, marca, valor) values (359, 'Fonte', 'MSI', 2487.88);
insert into produto (idProduto, nome, marca, valor) values (360, 'Teclado', 'Colorful', 12017.81);
insert into produto (idProduto, nome, marca, valor) values (361, 'CPU Cooler', 'Gigabyte', 3401.09);
insert into produto (idProduto, nome, marca, valor) values (362, 'Pasta Térmica', 'Biostar', 13741.61);
insert into produto (idProduto, nome, marca, valor) values (363, 'Pasta Térmica', 'Colorful', 6612.37);
insert into produto (idProduto, nome, marca, valor) values (364, 'Gabinete', 'Zadak', 13182.65);
insert into produto (idProduto, nome, marca, valor) values (365, 'Monitor', 'Lian Li', 1004.16);
insert into produto (idProduto, nome, marca, valor) values (366, 'Pasta Térmica', 'Biostar', 11636.08);
insert into produto (idProduto, nome, marca, valor) values (367, 'Gabinete', 'Vinik', 4355.88);
insert into produto (idProduto, nome, marca, valor) values (368, 'Placa de rede', 'Evga', 1277.37);
insert into produto (idProduto, nome, marca, valor) values (369, 'Mousepad', 'G.Skill', 9126.58);
insert into produto (idProduto, nome, marca, valor) values (370, 'Placa de som', 'Powercolor', 10551.12);
insert into produto (idProduto, nome, marca, valor) values (371, 'CPU Cooler', 'G.Skill', 9891.67);
insert into produto (idProduto, nome, marca, valor) values (372, 'Thermal Pad', 'Gigabyte', 6977.0);
insert into produto (idProduto, nome, marca, valor) values (373, 'CPU Cooler', 'Zadak', 1581.45);
insert into produto (idProduto, nome, marca, valor) values (374, 'Notebook', 'Vinik', 6814.1);
insert into produto (idProduto, nome, marca, valor) values (375, 'Placa de som', 'MSI', 7683.43);
insert into produto (idProduto, nome, marca, valor) values (376, 'Placa de rede', 'Lian Li', 8647.49);
insert into produto (idProduto, nome, marca, valor) values (377, 'SSD', 'MSI', 4088.34);
insert into produto (idProduto, nome, marca, valor) values (378, 'Memória RAM', 'Powercolor', 3874.58);
insert into produto (idProduto, nome, marca, valor) values (379, 'Pasta Térmica', 'MSI', 3126.24);
insert into produto (idProduto, nome, marca, valor) values (380, 'Pasta Térmica', 'Evga', 11076.16);
insert into produto (idProduto, nome, marca, valor) values (381, 'Monitor', 'Vinik', 3560.83);
insert into produto (idProduto, nome, marca, valor) values (382, 'SSD', 'Zadak', 14353.52);
insert into produto (idProduto, nome, marca, valor) values (383, 'Mouse', 'G.Skill', 12122.69);
insert into produto (idProduto, nome, marca, valor) values (384, 'Teclado', 'Zadak', 5609.02);
insert into produto (idProduto, nome, marca, valor) values (385, 'Thermal Pad', 'Zadak', 14109.23);
insert into produto (idProduto, nome, marca, valor) values (386, 'HD', 'Colorful', 13767.04);
insert into produto (idProduto, nome, marca, valor) values (387, 'Mousepad', 'Vinik', 7676.33);
insert into produto (idProduto, nome, marca, valor) values (388, 'SSD', 'Asrock', 14211.97);
insert into produto (idProduto, nome, marca, valor) values (389, 'Headset', 'Biostar', 1028.63);
insert into produto (idProduto, nome, marca, valor) values (390, 'Placa-mãe', 'Vinik', 3173.3);
insert into produto (idProduto, nome, marca, valor) values (391, 'Thermal Pad', 'Asus', 8231.34);
insert into produto (idProduto, nome, marca, valor) values (392, 'Pasta Térmica', 'Asus', 5705.13);
insert into produto (idProduto, nome, marca, valor) values (393, 'Mousepad', 'Lian Li', 3032.13);
insert into produto (idProduto, nome, marca, valor) values (394, 'Notebook', 'MSI', 723.94);
insert into produto (idProduto, nome, marca, valor) values (395, 'Mousepad', 'Evga', 1741.9);
insert into produto (idProduto, nome, marca, valor) values (396, 'Mouse', 'Vinik', 13363.16);
insert into produto (idProduto, nome, marca, valor) values (397, 'Placa de rede', 'Lian Li', 11622.27);
insert into produto (idProduto, nome, marca, valor) values (398, 'Monitor', 'Asrock', 8480.82);
insert into produto (idProduto, nome, marca, valor) values (399, 'Placa de Video', 'Biostar', 1395.73);
insert into produto (idProduto, nome, marca, valor) values (400, 'SSD', 'G.Skill', 9859.74);
insert into produto (idProduto, nome, marca, valor) values (401, 'Teclado', 'Zadak', 13029.89);
insert into produto (idProduto, nome, marca, valor) values (402, 'Mouse', 'Vinik', 4583.27);
insert into produto (idProduto, nome, marca, valor) values (403, 'Headset', 'Asrock', 3710.32);
insert into produto (idProduto, nome, marca, valor) values (404, 'Processador', 'Zadak', 1699.87);
insert into produto (idProduto, nome, marca, valor) values (405, 'Fonte', 'Biostar', 8697.76);
insert into produto (idProduto, nome, marca, valor) values (406, 'Teclado', 'Asus', 2577.43);
insert into produto (idProduto, nome, marca, valor) values (407, 'Pasta Térmica', 'Lian Li', 6440.84);
insert into produto (idProduto, nome, marca, valor) values (408, 'SSD', 'Biostar', 5240.94);
insert into produto (idProduto, nome, marca, valor) values (409, 'Placa-mãe', 'Asrock', 2340.96);
insert into produto (idProduto, nome, marca, valor) values (410, 'Teclado', 'Asus', 6761.73);
insert into produto (idProduto, nome, marca, valor) values (411, 'CPU Cooler', 'Biostar', 9899.62);
insert into produto (idProduto, nome, marca, valor) values (412, 'Fonte', 'Asrock', 6435.26);
insert into produto (idProduto, nome, marca, valor) values (413, 'HD', 'Asus', 13565.0);
insert into produto (idProduto, nome, marca, valor) values (414, 'Placa de rede', 'Powercolor', 13769.14);
insert into produto (idProduto, nome, marca, valor) values (415, 'Placa de Video', 'G.Skill', 4868.39);
insert into produto (idProduto, nome, marca, valor) values (416, 'Pasta Térmica', 'Vinik', 9952.03);
insert into produto (idProduto, nome, marca, valor) values (417, 'CPU Cooler', 'Gigabyte', 12611.54);
insert into produto (idProduto, nome, marca, valor) values (418, 'Monitor', 'Zadak', 6741.52);
insert into produto (idProduto, nome, marca, valor) values (419, 'SSD', 'Asus', 13398.25);
insert into produto (idProduto, nome, marca, valor) values (420, 'Pasta Térmica', 'Evga', 5698.13);
insert into produto (idProduto, nome, marca, valor) values (421, 'Processador', 'Zadak', 3289.06);
insert into produto (idProduto, nome, marca, valor) values (422, 'SSD', 'Zadak', 3046.23);
insert into produto (idProduto, nome, marca, valor) values (423, 'Mouse', 'Gigabyte', 8442.97);
insert into produto (idProduto, nome, marca, valor) values (424, 'Notebook', 'Gigabyte', 2901.15);
insert into produto (idProduto, nome, marca, valor) values (425, 'HD', 'Asrock', 6309.67);
insert into produto (idProduto, nome, marca, valor) values (426, 'Monitor', 'Zadak', 10835.6);
insert into produto (idProduto, nome, marca, valor) values (427, 'Notebook', 'Asus', 7572.84);
insert into produto (idProduto, nome, marca, valor) values (428, 'SSD', 'Lian Li', 8391.79);
insert into produto (idProduto, nome, marca, valor) values (429, 'Mousepad', 'Evga', 13095.92);
insert into produto (idProduto, nome, marca, valor) values (430, 'Gabinete', 'Vinik', 14418.34);
insert into produto (idProduto, nome, marca, valor) values (431, 'Notebook', 'Biostar', 4882.56);
insert into produto (idProduto, nome, marca, valor) values (432, 'Mouse', 'Zadak', 601.42);
insert into produto (idProduto, nome, marca, valor) values (433, 'Pasta Térmica', 'Zadak', 2224.54);
insert into produto (idProduto, nome, marca, valor) values (434, 'Placa de Video', 'G.Skill', 8111.24);
insert into produto (idProduto, nome, marca, valor) values (435, 'Pasta Térmica', 'Colorful', 826.86);
insert into produto (idProduto, nome, marca, valor) values (436, 'Placa-mãe', 'Zadak', 4347.69);
insert into produto (idProduto, nome, marca, valor) values (437, 'Notebook', 'Vinik', 2125.35);
insert into produto (idProduto, nome, marca, valor) values (438, 'Memória RAM', 'Asrock', 9017.34);
insert into produto (idProduto, nome, marca, valor) values (439, 'Processador', 'MSI', 7852.5);
insert into produto (idProduto, nome, marca, valor) values (440, 'Mouse', 'Lian Li', 7685.87);
insert into produto (idProduto, nome, marca, valor) values (441, 'HD', 'Zadak', 3692.8);
insert into produto (idProduto, nome, marca, valor) values (442, 'Pasta Térmica', 'Colorful', 6527.76);
insert into produto (idProduto, nome, marca, valor) values (443, 'Processador', 'Lian Li', 13096.76);
insert into produto (idProduto, nome, marca, valor) values (444, 'Headset', 'Lian Li', 12091.34);
insert into produto (idProduto, nome, marca, valor) values (445, 'Fonte', 'Gigabyte', 14215.39);
insert into produto (idProduto, nome, marca, valor) values (446, 'Thermal Pad', 'Evga', 13505.37);
insert into produto (idProduto, nome, marca, valor) values (447, 'Teclado', 'Evga', 13818.03);
insert into produto (idProduto, nome, marca, valor) values (448, 'Placa-mãe', 'Asus', 3312.5);
insert into produto (idProduto, nome, marca, valor) values (449, 'Placa de Video', 'Biostar', 4526.6);
insert into produto (idProduto, nome, marca, valor) values (450, 'Placa de Video', 'Lian Li', 7441.07);
insert into produto (idProduto, nome, marca, valor) values (451, 'HD', 'Vinik', 5693.65);
insert into produto (idProduto, nome, marca, valor) values (452, 'Mouse', 'Colorful', 5026.8);
insert into produto (idProduto, nome, marca, valor) values (453, 'Notebook', 'G.Skill', 671.67);
insert into produto (idProduto, nome, marca, valor) values (454, 'Processador', 'G.Skill', 7705.29);
insert into produto (idProduto, nome, marca, valor) values (455, 'Thermal Pad', 'MSI', 11822.54);
insert into produto (idProduto, nome, marca, valor) values (456, 'SSD', 'Asrock', 2368.09);
insert into produto (idProduto, nome, marca, valor) values (457, 'Mouse', 'Powercolor', 814.51);
insert into produto (idProduto, nome, marca, valor) values (458, 'HD', 'Gigabyte', 10862.32);
insert into produto (idProduto, nome, marca, valor) values (459, 'Monitor', 'Lian Li', 6364.83);
insert into produto (idProduto, nome, marca, valor) values (460, 'Placa-mãe', 'Biostar', 2501.14);
insert into produto (idProduto, nome, marca, valor) values (461, 'Mousepad', 'Lian Li', 8609.56);
insert into produto (idProduto, nome, marca, valor) values (462, 'Monitor', 'G.Skill', 2760.81);
insert into produto (idProduto, nome, marca, valor) values (463, 'Gabinete', 'MSI', 1522.93);
insert into produto (idProduto, nome, marca, valor) values (464, 'Placa de rede', 'Vinik', 5964.1);
insert into produto (idProduto, nome, marca, valor) values (465, 'Placa de Video', 'Zadak', 11806.58);
insert into produto (idProduto, nome, marca, valor) values (466, 'Memória RAM', 'Gigabyte', 7776.01);
insert into produto (idProduto, nome, marca, valor) values (467, 'HD', 'Evga', 7841.75);
insert into produto (idProduto, nome, marca, valor) values (468, 'Teclado', 'Asrock', 12352.98);
insert into produto (idProduto, nome, marca, valor) values (469, 'Memória RAM', 'Zadak', 7042.88);
insert into produto (idProduto, nome, marca, valor) values (470, 'Placa de Video', 'Zadak', 2411.72);
insert into produto (idProduto, nome, marca, valor) values (471, 'HD', 'Lian Li', 9765.72);
insert into produto (idProduto, nome, marca, valor) values (472, 'SSD', 'Zadak', 754.67);
insert into produto (idProduto, nome, marca, valor) values (473, 'Pasta Térmica', 'Powercolor', 9461.21);
insert into produto (idProduto, nome, marca, valor) values (474, 'Notebook', 'Asus', 12579.65);
insert into produto (idProduto, nome, marca, valor) values (475, 'Placa de rede', 'Evga', 4088.22);
insert into produto (idProduto, nome, marca, valor) values (476, 'Mouse', 'Gigabyte', 3727.04);
insert into produto (idProduto, nome, marca, valor) values (477, 'Fonte', 'Colorful', 10656.98);
insert into produto (idProduto, nome, marca, valor) values (478, 'Fonte', 'Colorful', 13361.85);
insert into produto (idProduto, nome, marca, valor) values (479, 'Gabinete', 'Powercolor', 9077.96);
insert into produto (idProduto, nome, marca, valor) values (480, 'Pasta Térmica', 'G.Skill', 1551.07);
insert into produto (idProduto, nome, marca, valor) values (481, 'Notebook', 'Zadak', 10056.93);
insert into produto (idProduto, nome, marca, valor) values (482, 'Fonte', 'Asrock', 7663.07);
insert into produto (idProduto, nome, marca, valor) values (483, 'Gabinete', 'G.Skill', 4177.18);
insert into produto (idProduto, nome, marca, valor) values (484, 'Fonte', 'Asus', 163.6);
insert into produto (idProduto, nome, marca, valor) values (485, 'SSD', 'Asrock', 8349.49);
insert into produto (idProduto, nome, marca, valor) values (486, 'Pasta Térmica', 'Asrock', 9221.32);
insert into produto (idProduto, nome, marca, valor) values (487, 'Gabinete', 'Asrock', 4146.84);
insert into produto (idProduto, nome, marca, valor) values (488, 'Mouse', 'Gigabyte', 9351.12);
insert into produto (idProduto, nome, marca, valor) values (489, 'Notebook', 'G.Skill', 4646.98);
insert into produto (idProduto, nome, marca, valor) values (490, 'Teclado', 'Colorful', 5241.08);
insert into produto (idProduto, nome, marca, valor) values (491, 'Headset', 'G.Skill', 7705.45);
insert into produto (idProduto, nome, marca, valor) values (492, 'Placa de Video', 'MSI', 494.63);
insert into produto (idProduto, nome, marca, valor) values (493, 'SSD', 'Vinik', 10738.92);
insert into produto (idProduto, nome, marca, valor) values (494, 'Gabinete', 'Powercolor', 14340.86);
insert into produto (idProduto, nome, marca, valor) values (495, 'Gabinete', 'Evga', 13719.54);
insert into produto (idProduto, nome, marca, valor) values (496, 'Processador', 'Powercolor', 494.44);
insert into produto (idProduto, nome, marca, valor) values (497, 'Processador', 'Evga', 6006.91);
insert into produto (idProduto, nome, marca, valor) values (498, 'Monitor', 'Biostar', 14887.98);
insert into produto (idProduto, nome, marca, valor) values (499, 'Mousepad', 'Colorful', 1022.02);
insert into produto (idProduto, nome, marca, valor) values (500, 'Pasta Térmica', 'Zadak', 11387.53);
